leftnav:
- identifier: b52b8631-f3a0-a8cb-3361-2e8150130c29
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: aac563f0-008f-8d39-a7cf-5bbe3070cddb
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 3ae7be5e-771e-489e-64b5-7515a7f2ac3c
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: bb9bc615-4a3f-1901-b301-05cf57e460ca
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: c554d79a-3f04-22bc-ecf4-7f40a4c0b17b
  name: Exams
  pageRef: /pages/exams
  weight: 50
- identifier: 0d6abafb-55bb-d2d0-610e-ff377147d3aa
  name: Projects
  pageRef: /pages/projects
  weight: 60
